"""add panel fields and panel_parameters

Revision ID: 4f98c4fb3508
Revises: 92cd83c262f5
Create Date: 2026-09-16 14:00:11.155444

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4f98c4fb3508'
down_revision = '92cd83c262f5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('panel_parameters',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('panel_id', sa.Integer(), nullable=False),
    sa.Column('test_id', sa.Integer(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['panel_id'], ['tests.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['test_id'], ['tests.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('panel_id', 'test_id', name='uq_panel_test')
    )
    with op.batch_alter_table('panel_parameters', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_panel_parameters_panel_id'), ['panel_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_panel_parameters_test_id'), ['test_id'], unique=False)

    with op.batch_alter_table('tests', schema=None) as batch_op:
        batch_op.add_column(sa.Column('result_format', sa.String(length=20), nullable=False))
        batch_op.add_column(sa.Column('is_panel', sa.Boolean(), nullable=False))
        batch_op.add_column(sa.Column('sort_order', sa.Integer(), nullable=False))
        batch_op.create_index(batch_op.f('ix_tests_is_panel'), ['is_panel'], unique=False)
        batch_op.create_index(batch_op.f('ix_tests_result_format'), ['result_format'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tests', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_tests_result_format'))
        batch_op.drop_index(batch_op.f('ix_tests_is_panel'))
        batch_op.drop_column('sort_order')
        batch_op.drop_column('is_panel')
        batch_op.drop_column('result_format')

    with op.batch_alter_table('panel_parameters', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_panel_parameters_test_id'))
        batch_op.drop_index(batch_op.f('ix_panel_parameters_panel_id'))

    op.drop_table('panel_parameters')
    # ### end Alembic commands ###
