"""Add last_login to users

Revision ID: 885dca2c5f65
Revises: f33a960ff3d3
Create Date: 2026-09-15 12:59:30.759726

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '885dca2c5f65'
down_revision = 'f33a960ff3d3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('last_login', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('last_login')

    # ### end Alembic commands ###
