"""add lab_settings table for branding

Revision ID: d703fa88752f
Revises: 4f6b27f9dd9c
Create Date: 2026-09-15 16:47:48.061399

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd703fa88752f'
down_revision = '4f6b27f9dd9c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('lab_settings',
    sa.Column('lab_name', sa.String(length=150), nullable=False),
    sa.Column('tagline', sa.String(length=200), nullable=True),
    sa.Column('logo_filename', sa.String(length=255), nullable=True),
    sa.Column('address', sa.String(length=255), nullable=True),
    sa.Column('phone', sa.String(length=50), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('website', sa.String(length=150), nullable=True),
    sa.Column('license_no', sa.String(length=80), nullable=True),
    sa.Column('footer_note', sa.String(length=255), nullable=True),
    sa.Column('primary_color', sa.String(length=20), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('lab_settings')
    # ### end Alembic commands ###
